spring.application.name=sb-ecom

## For MongoDB properties
spring.data.mongodb.url=mongodb://localhost:27017/sb_ecom
##spring.data.mongodb.database=local_mongodb
spring.data.mongodb.auto-index-creation=true

project.image=/uploads/image/

spring.app.jwtSecret=UkJx9j8JF0xJk73FQ2pF6s8mW4rT1uHpZ6eN0yPaVbKdX3qLs9YmGh5cDtR2Vx
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookieName=springBootEcom

logging.level.com.ecommerce.sb_ecom=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.comexample.securitydemo=DEBUG

